-- MySQL Script generated by MySQL Workbench
-- Sun May 14 08:17:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `NIT` INT NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `NIT` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Portal` VARCHAR(45) NULL,
  PRIMARY KEY (`NIT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sales_h`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sales_h` (
  `Numero` INT NOT NULL,
  `Serie` INT NOT NULL,
  `Fecha` DATE NULL,
  `CodCliente` INT NOT NULL,
  `NIT` INT NOT NULL,
  PRIMARY KEY (`Numero`, `Serie`),
  INDEX `CodClie_idx` (`CodCliente` ASC) VISIBLE,
  INDEX `nit_idx` (`NIT` ASC) VISIBLE,
  CONSTRAINT `CodClie`
    FOREIGN KEY (`CodCliente`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nit`
    FOREIGN KEY (`NIT`)
    REFERENCES `mydb`.`Company` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `idProducts` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Id_marca` INT NULL,
  `id_categoria` INT NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rates1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rates1` (
  `idrates1` INT NOT NULL,
  `Costo` INT NULL,
  `precio` INT NULL,
  `rt_state` VARCHAR(45) NULL,
  PRIMARY KEY (`idrates1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sales_d`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sales_d` (
  `id` INT NOT NULL,
  `Cantidad` INT NULL,
  `Articulo` INT NOT NULL,
  `Factura` INT NOT NULL,
  `Serie` INT NOT NULL,
  `Rate` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `art_idx` (`Articulo` ASC) VISIBLE,
  INDEX `fact_idx` (`Factura` ASC) VISIBLE,
  INDEX `serie_idx` (`Serie` ASC) VISIBLE,
  INDEX `rates_idx` (`Rate` ASC) VISIBLE,
  CONSTRAINT `art`
    FOREIGN KEY (`Articulo`)
    REFERENCES `mydb`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fact`
    FOREIGN KEY (`Factura`)
    REFERENCES `mydb`.`Sales_h` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `serie`
    FOREIGN KEY (`Serie`)
    REFERENCES `mydb`.`Sales_h` (`Serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rates`
    FOREIGN KEY (`Rate`)carrera
    REFERENCES `mydb`.`rates1` (`idrates1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
