-- MySQL Script generated by MySQL Workbench
-- Sat May 27 16:12:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
create  SCHEMA `ProyectoBDD2` ;
USE `ProyectoBDD2` ;

-- -----------------------------------------------------
-- Table `mydb`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBDD2`.`Articulo` (
  `IdArt` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `PrecioCompra` DOUBLE NULL,
  `PrecioVenta` DOUBLE NULL,
  `CantidadComprada` INT NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`IdArt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBDD2`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `CodArticulo` INT NULL,
  `CodCliente` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `Cantidad` INT NULL,
  `precioUnidad` DOUBLE NULL,
  `totalPagar` DOUBLE NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `ventArt_idx` (`CodArticulo` ASC) VISIBLE,
  CONSTRAINT `ventArt`
    FOREIGN KEY (`CodArticulo`)
    REFERENCES `ProyectoBDD2`.`Articulo` (`IdArt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert  into articulo (nombre, descripcion, preciocompra, precioventa, cantidadcomprada) 
		values ("agua", "botella", 1.5,3.00,50)
        
select * from Articulo

INSERT INTO `proyectobdd2`.`ventas` (`CodArticulo`, `CodCliente`, `nombre`, `Cantidad`, `precioUnidad`, `totalPagar`) VALUES ('1', '1', 'juan', '3', '3', '9');
INSERT INTO `proyectobdd2`.`ventas` (`CodArticulo`, `CodCliente`, `nombre`, `Cantidad`, `precioUnidad`, `totalPagar`) VALUES ('1', '1', 'juan', '3', '3', '9');
select * from ventas

commit 
